### ISSUE TITLE
Hashtags not being removed since version 2

### ISSUE THREAD

**Issue by bartvanremortele** [stiang/remove-markdown#22]
Version 2 does not strip hashtags from the input string.

`hodor\n\n#Hello World!\n\nTest`
should output:
`hodor\n\nHello World!\n\nTest`
but it outputs:
`hodor\n\n#Hello World!\n\nTest`

**Comment by stiang** [comment]
Actually, that’s the expected behavior. You are right that this changed between 0.1.0 and 0.2.0, but the original behavior was wrong:

http://spec.commonmark.org/0.27/#atx-headings

So, there needs to be a space between the `#` characters and the heading name for it to be considered a Markdown heading. I feel that this library *should* leave actual hashtags intact, at least with the default options. See example 34 here:

http://spec.commonmark.org/0.27/#example-34

I guess I haven’t specified anywhere which spec this library follows, but I feel pretty strongly that CommonMark is the way to go. However, I am open to feedback on this.

**Comment by bartvanremortele** [comment]
Ok, your explanation makes sense. I'll take a look how this impacts our implementation. Thank you for your swift feedback!

**Comment by stiang** [comment]
It would be nice to have an option for this, so a PR would be merged quite quickly :)
